version: "3"
services:
    redis:
        image: redis:latest
        container_name: redis-container
        restart: always
        ports:
            - 6379:6379
    zookeeper:
        image: zookeeper:latest
        container_name: zookeeper-container
        restart: always
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
            - 8080:8080
    mongodb:
        image: mongo:latest
        container_name: mongodb-container
        restart: always
        ports:
            - 27017:27017
    spring-tiny-link-generator-api:
        image: spring-tiny-link-generator-api:latest
        container_name: spring-tiny-link-generator-api
        restart: always
        ports:
            - 7787:7787
        links:
          - redis
          - zookeeper
          - mongodb